### ISSUE TITLE
ImportError: Error relocating .../_perlin.cpython-37m-x86_64-linux-gnu.so: grad2: symbol not found

### ISSUE THREAD

**Issue by lc-thomas** [caseman/noise#28]
Hello,
I'm trying to use the noise library from inside docker alpine.
Installing noise with pip is okay, but when I try to import it I get this error message :
```

Traceback (most recent call last):
  File "map_generator.py", line 1, in <module>
    import noise
  File "/usr/lib/python3.7/site-packages/noise/__init__.py", line 12, in <module>
    from . import _perlin, _simplex
ImportError: Error relocating /usr/lib/python3.7/site-packages/noise/_perlin.cpython-37m-x86_64-linux-gnu.so: grad2: symbol not found
```

Any idea on how to fix this ?

**Comment by adwaithhs** [comment]
It got fixed when I used distutils.core instead of setuptools in the [setup.py](https://github.com/caseman/noise/blob/master/setup.py). Not sure if this is **the** solution.

before
```try:
    from setuptools import setup, Extension
except ImportError:
    from distutils.core import setup, Extension
```
after
`from distutils.core import setup, Extension
`
